# https://docs.cortex.io/docs/reference/basics/entities#service-entities

openapi: 3.0.1
info:
  title: Workleap Authentication Client Credentials Grant
  description: Set of two libraries enabling authenticated machine-to-machine HTTP communication between a .NET application and an ASP.NET Core web application
  x-cortex-git:
    github:
      alias: gsoft-inc
      repository: gsoft-inc/wl-authentication-clientcredentialsgrant
  x-cortex-tag: service-wl-authentication-clientcredentialsgrant
  x-cortex-type: library
  x-cortex-slack:
    channels:
      - name: internal-dev-platform
        notificationsEnabled: true
  x-cortex-owners:
    - name: team-internal-developer-platform-backend
      type: GROUP
      provider: CORTEX
  x-cortex-link:
    - name: Documentation
      type: documentation
      url: https://gsoftdev.atlassian.net/wiki/spaces/TEC/pages/3578003702
    - url: https://github.com/gsoft-inc/wl-authentication-clientcredentialsgrant/.cortex/catalog/service-wl-authentication-clientcredentialsgrant.yaml
      name: Edit current Cortex entity in GitHub
      type: cortex
