name: CI

on:
  pull_request:
    branches: ["main"]
    paths-ignore: ["*.md"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4 # Install version declared in global.json
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            7.0.x

      - run: ./Build.ps1
        shell: pwsh
